### ISSUE TITLE
may god have mercy on your souls

### ISSUE THREAD

**Issue by rezemoe** [Sheppsu/oct-site#1]
for the love of god don't use filters 😭

**Comment by Sheppsu** [comment]
please elaborate misha 😭

**Comment by hrfarmer** [comment]
o, why?

**Comment by Sheppsu** [comment]
oh it's hrfarmer's change lol I'm safe

**Comment by hrfarmer** [comment]
TF U MEAN???

**Comment by Sheppsu** [comment]
average hr farmer L

**Comment by rezemoe** [comment]
filters in css are unstable and give unpredicted result from browser to browser, as well as using `invert` is absolutely stupid since it recolors everything. do not use filters if  you dont need edge cases idk blur, but blur is fucky wucky too, especially if it's `backdrop-filter`, backdrops are not even supported by most browsers yet

**Comment by Sheppsu** [comment]
bro really ghosted you on this... I'll look into fixing this later if hr farmer doesn't

**Comment by hrfarmer** [comment]
i don’t really see the issue with using this specific filter because 

1. what i’m trying to do is not that complex, don’t really see how there could be any major difference between browsers. i can check though to make sure it works correctly 
2. the whole reason i’m using invert is so the image entirely inverts lol

**Comment by Sheppsu** [comment]
closing cuz inactivity
